import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleAnalytics } from '@next/third-parties/google';
import "./globals.css";
// import ErrorBoundary from '@/components/ErrorBoundary';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*<ErrorBoundary>*/}
      <body className={inter.className}><div>GA Test1</div>{children}</body>
      {/*</ErrorBoundary>*/}
      <GoogleAnalytics gaId="G-0YWG600C1W" />
    </html>
  );
}
