name: Test by jest

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'  # Your node version, default 20 in 2024

      - name: Install Dependencies
        run: yarn

      - name: Run Test
        run: yarn test
